#!/bin/bash

SIZE=$1

for((i=0;i<$SIZE;i++)); do {
 for((j=0;j<$SIZE;j++)); do {
 dist=$(echo "sqrt(($i - $j)^2)" | bc -l)
 #dist=$(echo "abs($i - $j)" | bc -l)
dist=$(echo $dist | cut -f 1 -d ".")
 echo "    (distance x$i x$j d$dist)"
 echo "    (distance y$i y$j d$dist)"

 }; done
}; done
