#!/bin/bash

SIZE=$1

SZM=`expr $SIZE - 1`
for((i=0;i<$SZM;i++)); do {
 j=$i
 j=`expr $i + 1`
# echo $j
# for((;j<$SIZE;j++)); do {
 echo "    (succ x$i x$j)"
 echo "    (succ y$i y$j)"
 
# }; done
}; done
